spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/notice?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Rhksgh12!
    tomcat:
      max-active: 100
      test-on-borrow: true
      validation-query: SELECT 1
      validation-interval: 30000
      login-timeout: 3000


mybatis:
  configuration.map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*-mapper.xml

logging:
  level:
    "[org.hibernate]": debug

session:
  setMaxInactiveInterval: 60

